### PR TITLE
[TAS-374] BE feat: sync auth system with ekkozulu

### PR DESCRIPTION
**Pull request by axelgcd**
Copied ekkozulu auth system

use [this](https://github.com/undermilli/lolhub-web/pull/64) version of front end to test.

Most of accounts don't have mail registered so you can either connect with axel.guichard@utt.fr and password Test1234 or signup wiuth a new accout because you wont be able to sign in with an old account

(don't forget to get .env on slack)

### CODE REVIEW

**Comment by aknur1999** [comment]
@axelgcd after logging in with your account, on the main page, when I refresh the page, I am getting this error:
Screenshot 2024-04-25 at 5 13 43 PM

**Comment by aknur1999** [comment]
@axelgcd when I logged in it redirects me to dashboard (my page) page, I think it should redirect to main page, right?

**Comment by axelgcd** [comment]
> @axelgcd when I logged in it redirects me to dashboard (my page) page, I think it should redirect to main page, right?

fixed!

**Review by aknur1999 — APPROVED** [review]

**Review by ivxvi12 — APPROVED** [review]
LGTM

**Pull request merged**
